---
- name: 'copy python app from repo'
  copy:
    remote_src: true
    src: '{{ tmp_dir }}/app/python'
    dest: '{{ app_dir }}'
    owner: '{{ player_name }}'
    group: '{{ group_name }}'
    mode: '0755'

- name: 'update pip3 for python3.7'
  command: 'python3.7 -m pip install --upgrade pip'

- name: 'pip install'
  command: 'python3.7 -m pip install -r {{ app_dir }}/python/requirements.txt'
