---
- name: 'put systemd file for all apps'
  template:
    src: app.service.j2
    dest: /etc/systemd/system/niita_{{ item.name }}.service
  loop:
    - { name: python, command: '/usr/bin/python3.7 ./app.py' }
    - { name: ruby, command: '/usr/local/bin/bundle exec rackup -p 5000' }
    - { name: go, command: '/usr/bin/go run app.go structure.go db_utility.go' }
    - { name: node, command: '/usr/local/bin/node app.js' }
  notify: reload systemd
